<a href="https://colab.research.google.com/github/Akash-awan83/Numpy_Practice_CheatSheet/blob/main/Numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(a[0][1][1])

6


# Slicing Array

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[3:10])
print(arr[1::2])

[4 5 6 7 8]
[2 4 6 8]


In [ ]:
arr2=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[["a","b","c","d","e"],["e","f","g","h","i"],["aa","bb","cc","dd","ee"]]])
print(arr2)
arr2[0:2,0:3,1:3]

[[['1' '2' '3' '4' '5']
  ['6' '7' '8' '9' '10']
  ['11' '12' '13' '14' '15']]

 [['a' 'b' 'c' 'd' 'e']
  ['e' 'f' 'g' 'h' 'i']
  ['aa' 'bb' 'cc' 'dd' 'ee']]]


array([[['2', '3'],
        ['7', '8'],
        ['12', '13']],

       [['b', 'c'],
        ['f', 'g'],
        ['bb', 'cc']]], dtype='<U21')

## 1D Array[start:end]
## 2D Array[Rows ,columns]
## 3D Array[layers,rows,columns]
## 4D Array[block,layer,rows,columns]

In [ ]:
arr=np.array([[[[1,2,3,4,5],[6,7,8,9,0]]],[[[11,12,13,14,15],[16,17,18,19,20]]]])
print(arr[0,0,::-1,::-1])
print(arr.ndim)
# print(arr)


[[0 9 8 7 6]
 [5 4 3 2 1]]
4


In [ ]:
arr=np.array([[[1,2,3,4,5],['a','b','c','d','e']],[[1,2,3,4,5],['a','b','c','d','e']],[[1,2,3,4,5],['a','b','c','d','e']]])
arr[0:,1,0:]

array([['a', 'b', 'c', 'd', 'e'],
       ['a', 'b', 'c', 'd', 'e'],
       ['a', 'b', 'c', 'd', 'e']], dtype='<U21')

In [ ]:
import numpy as np

# 3D array banate hain
arr_3d = np.array([[[1, 2, 3,4], [4, 5, 6,5]], [[7, 8, 9,6], [10, 11, 12,8]], [[13, 14, 15,9], [16, 17, 18,3]]])

# Har 2nd slice, row aur column ko pick kar rahe hain
sliced_arr_3d = arr_3d[0::2, 0::2, 0::2]

print(sliced_arr_3d)


[[[ 1  3]]

 [[13 15]]]


# Adding Multiplying concatinating 2D and 3D arrays

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[0,3:]+arr[1,3:])


[13  5]


In [ ]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
arr[0,:,3:]*arr[1,:,3:]

array([[16, 25],
       [81,  0]])

# Numpy Data Types

i for integer

b for boolean

u for unsigned integer

f for float

c for complex float

m for time delta

M for data time

O for object

S for string

U for unicode string

V for memory

# View and copy in python


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr2=arr.copy()
arr2[0]=100
print(arr)
print(arr2)
arr3=arr.view()
print(arr3)


[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]


## Array shape

Array  has an attribute shape which tells us that  how many dimensions it has how many elements every dimension has


In [ ]:
class MyArray:
    def __init__(self, data):
        self.data = data

    @property
    def shape(self):
        rows = len(self.data)         # Total rows (outer list length)
        cols = len(self.data[0])      # Total columns (inner list length)
        return (rows, cols)           # Return shape as a tuple

# Ab ek object banate hain
my_array = MyArray([[1, 2, 3], [4, 5, 6]])
print(my_array)

# 'shape' ko directly access karte hain bina () ke
print(my_array.shape)  # Output: (2, 3)


(2, 3)


# Array Reshape

# hum 2D ya 3D ko 1D mai yaa kisi b dimension ko kisi b dimension mai convert kr skty hain  .or -1 as a assistant kam krta hai python automatically total number of elements sy divide kr dyta hai jo numbers hum ny diye hoty hain un sy

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.reshape(2,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr.reshape(2,5,-1)
#python did total number of elements:10 /2*5=1

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

# ** Numpy Iteration**

# numpy arrays   ko iterate kiya jaa skta hai  du triko sy ak tu nested loops use kr k or dosra simple loop use kr k os k sth nditer use kr k  or is k sth hum slicing b kr skty hain numpy arrays k loop k andr


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(arr[:,:,::2]):
    print(i)

1
3
4
6
7
9
10
12


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in arr[0:,::2]:
    for j in i:
        print(j)

1
3
5
7


# **Numpy Array Concatination**

# numpy array ko concatinate krny k liya concatinate ka use krty hain  or axis ka use krty hain or concatinate sirf or sirf ak dimension k liya he use hota hai



In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr3=np.concatenate((arr,arr2),axis=0)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
arr1=np.array([[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr2=np.concatenate((arr,arr1),axis=1)
print(arr2)


[[ 1  2  3  4  5  6]
 [ 1  2  3  7  8  9]
 [ 1  2  3 10 11 12]
 [ 1  2  3 13 14 15]]


In [ ]:
#axis 1 ka mtlb hota hai k row wise kr axis 0 ka mtlb hota hai index column wise or 2 index wise
# axis=2: Concatenates columns within each row, resulting in (3, 2, 4).
# axis=1: Concatenates rows within each matrix, resulting in (3, 4, 2).
# axis=0: Stacks matrices on top of each other, resulting in (6, 2, 2).
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
arr1=np.array([[[13,14],[15,16]],[[17,18],[19,20]],[[21,22],[23,24]]])
arr2=np.concatenate((arr,arr1),axis=2)
arr3=np.concatenate((arr,arr1),axis=1)
arr4=np.concatenate((arr,arr1),axis=0)
print(arr2)
print(arr3)
print(arr4)

[[[ 1  2 13 14]
  [ 3  4 15 16]]

 [[ 5  6 17 18]
  [ 7  8 19 20]]

 [[ 9 10 21 22]
  [11 12 23 24]]]
[[[ 1  2]
  [ 3  4]
  [13 14]
  [15 16]]

 [[ 5  6]
  [ 7  8]
  [17 18]
  [19 20]]

 [[ 9 10]
  [11 12]
  [21 22]
  [23 24]]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]

 [[21 22]
  [23 24]]]


# **Stack in numpy array**

# Axis 1 ka stack: Arrays ko side-by-side rakh diya jata hai, columns badh jati hain.
# Axis 0 ka stack: Arrays ko upar neeche rakh diya jata hai, rows badh jati hain.
# **Axis 2 ka stack :dtack b use kr skty hain is ki jgaa pr or or yai ak ak kr k columns koo krtaa hai**
# 3 types hoti hain is kii vstack ,hstack ,dstack
# **Stacking adds a new dimension and then combines the arrays.**
# **Concatenation combines along the same dimension, adding more elements.**

In [ ]:

arr=([1,2,3])
ar=([4,5,6])
arr1=np.stack((arr,ar),axis=0)
arr2=np.stack((arr,ar),axis=1)
arr3=np.stack((arr,ar))
print(arr1)
print(arr2)
print(arr3)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr=([[1,2,3],[4,5,6]])
ar=([11,12,13],[7,8,9])
arr1=np.stack((arr,ar),axis=0)
arr2=np.stack((arr,ar),axis=1)
arr3=np.stack((arr,ar),axis=2)
print(arr1)
print(arr2)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [ 7  8  9]]]
[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [ 7  8  9]]]
[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4  7]
  [ 5  8]
  [ 6  9]]]


In [ ]:
arr=np.array([[[[1,2],[3,4],[5,6]]],[[[7,8],[9,10],[11,12]]]])
ar=np.array([[[[13,14],[15,16],[17,18]]],[[[19,20],[21,22],[23,24]]]])
Arr=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
Ar=np.array([[[13,14],[15,16]],[[19,20],[21,22]]])
arr1=np.hstack((Arr,Ar))
arr2=np.vstack((arr,ar))
arr3=np.dstack((arr,ar))
print(arr1)
print(arr2)
print(arr3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [13 14]
  [15 16]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [19 20]
  [21 22]]]
[[[[ 1  2]
   [ 3  4]
   [ 5  6]]]


 [[[ 7  8]
   [ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]
   [17 18]]]


 [[[19 20]
   [21 22]
   [23 24]]]]
[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [13 14]
   [15 16]
   [17 18]]]


 [[[ 7  8]
   [ 9 10]
   [11 12]
   [19 20]
   [21 22]
   [23 24]]]]


**## Split Arrays**

# split arrays mai b hsplit vsplit or dsplit hota hai or yai array ko tor dyta hai jitny hiso mai chaho or is ki khas baat yai hai k khud he arrange b kr lyta hai agr 7 elements hain tu  3 2 2 ka khud bna dy gaa agr ap is ko 3 mai convert kro gy
# **np.array_split just divides the original array into subarrays and stores them as elements of a list.**

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
arr=np.array_split(arr,3)#array ko 3 hiso mai tor diya
print(arr)
print(arr[0:2:2])
print(arr[1])
print(arr[2])


[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20])]
[30 40]
[50 60]


# np.hsplit(): Splits along horizontal axis (columns) in 2D arrays.
# np.vsplit(): Splits along vertical axis (rows) in 2D arrays.
# np.dsplit(): Splits along depth axis (axis 2) in 3D arrays.
# So, the main difference between these functions is the axis along which the array is split:
# hsplit: along columns (axis 1),
# vsplit: along rows (axis 0),
# dsplit: along depth (axis 2), but only works with 3D arrays.

In [ ]:
#using vsplit
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr=np.vsplit(arr,2)
print(arr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [ ]:
#using hsplit
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr=np.hsplit(arr,4)
print(arr)

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
arr=np.dsplit(arr,2)
print(arr)

[array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]]]), array([[[ 2],
        [ 4]],

       [[ 6],
        [ 8]],

       [[10],
        [12]]])]


## ** NUmpy Searching Arrays**

# you can search an array for a certain value and return the indexes to get the match by using where . np.where() khali array wapis krta hai agr conditon wrong ho jay is ki wja yai hai k agr yai error dyta tu hr baar code likhna prta error ko handle krny k liya


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
arr=np.where(arr%2==0)
print(arr)

#where jo hai wo index wapis krta hai
arr=np.array([5, 10, 15, 20, 25])
arr=np.where(arr==15)
print(arr)

(array([1, 3, 5, 7]),)
(array([2]),)


In [ ]:
arr=[2, 4, 6, 8, 10, 12, 14, 16]
arr=np.array(arr)
arr3=np.where(arr>10)
print(arr3)
#find odd numbers empty array is liya wapis kiya q k sary even hain ,tuple pr % operater use nahi ho skta
arr2=np.where(arr%2==1)
print(arr2)
#for 2D arrays
arr2=np.array([[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]])
arr3=np.where(arr2>=50)
print(arr3)#is ki out put ko is ny asy identify kiya hai k rows or column mai (0,1,2)rows or (0,1,2)columns First array (array([1, 1, 2, 2, 2])): These are the row indexes where the condition is true:

# 50 is in row 1
# 60 is in row 1
# 70 is in row 2
# 80 is in row 2
# 90 is in row 2
# Second array (array([1, 2, 0, 1, 2])): These are the column indexes where the condition is true:

# 50 is in column 1
# 60 is in column 2
# 70 is in column 0
# 80 is in column 1
# 90 is in column 2  default order of checking is row by row first, then column by column.


#Finding prime numbers
# Ak=np.array([[12, 17, 19],
#  [24, 35, 47],
#  [57, 89, 95]])
# arr=np.where(Ak%Ak==0 and Ak%1==0)
# print(arr)

(array([5, 6, 7]),)
(array([], dtype=int64),)
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


In [ ]:
#for prime number np.where
import numpy as np
Ak=np.array([[12, 17, 19],
 [24, 35, 47],
 [57, 89, 95]])



In [ ]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    for i in range(3, int(np.sqrt(n)) + 1, 2):
        if n % i == 0:
            return False
    return True
Ak = np.array([[12, 17, 19],
               [24, 35, 47],
               [57, 89, 95]])

# Create a boolean array where True indicates a prime number
prime_mask = np.vectorize(is_prime)(Ak)

# Use np.where to get indices of prime numbers
prime_indices = np.where(prime_mask)

print("Prime mask (boolean array):")
print(prime_mask)
print("\nIndices of prime numbers:")
print(prime_indices)

# Extract prime numbers from the original array using the indices
prime_numbers = Ak[prime_indices]

print("\nPrime numbers in the array:")
print(prime_numbers)


Prime mask (boolean array):
[[False  True  True]
 [False False  True]
 [False  True False]]

Indices of prime numbers:
(array([0, 0, 1, 2]), array([1, 2, 2, 1]))

Prime numbers in the array:
[17 19 47 89]


In [ ]:
import numpy as np
def is_prime(n):
  if n<=1:
    return False
  if n==2:
    return True
  if n%2==0:
    return False
  for i in range(3,int(np.sqrt(n))+1,2):
    if n%i==0:
      return False
  return True
is_prime(55)




False

# **Search sorted *

ak sorted array pr kam krta hai wo ya assending order mai hoti hai ya decending order mai hoti hai .mtlb k agr tm ak number add krna chhty hoo tu yai position btata hai k kis jgaa number add kiya ja skta hai bs index btata hai

In [ ]:
import numpy as np
#left kiya kam krta hai yai phly array dekhta osy dekhny k baad yai dekhtaa hai is array mai phly kis jga insert kiya jaa skta hai for example [1,3,3,4,5,6]
#is mai agr hum 3  ko insert krna chahty hain tu yai btay gaaa k 3 left sy phly kis jgaa insert kiya jaa skta hai 1 is ki output hoo gi
# is ko hum desending order mai b kr skty hain

arr=np.array([1,3,3,3,4,5,6])
arr=np.searchsorted(arr,3,side='left')
print(arr)

1


In [ ]:
#right kiya kam krta hai yai phly array dekhta  hai os k baad yai dekhta hai k kis jga number end hoa os k baad insert krta hai forxample [1,3,3,4,5,6]
#ab yai btay gaa 3 index pr nmbr add kr du q k os k aagy shru krna hai
arr=np.array([1,3,3,4,5,6])
arr=np.searchsorted(arr,3,side='right')
print(arr)

3


# Sorting Arrays

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr1=np.sort(arr)
print(arr1)
arr=np.array([[1,2,4,6,7,3,4,5],[1,2,5,4,3,6,7,9]])
arr=np.sort(arr)
print(arr)

[1 2 3 4 5 6]
[[1 2 3 4 4 5 6 7]
 [1 2 3 4 5 6 7 9]]


# **linspace**

In [ ]:
#linespace kisi b number ko equal parts mai dividde kr k un ki array banata hai
ar_lin=np.linspace(0,20,4)
print(ar_lin)


[ 0.          6.66666667 13.33333333 20.        ]


# **Random**

In [ ]:
# generate random number between 0 and 1
import numpy as np
arr=np.random.rand(5,5)
print(arr)


[[0.58396578 0.20051891 0.96174549 0.94840575 0.51346662]
 [0.55523137 0.94001956 0.18097839 0.10359913 0.17302456]
 [0.6759915  0.25878796 0.8951907  0.91035832 0.00913385]
 [0.01872311 0.79947643 0.45181643 0.6328713  0.47574675]
 [0.50700257 0.38430112 0.86045676 0.42570654 0.4562308 ]]


In [ ]:
#randn funtion is used to generate numbers close to zero


# **Arrange function**

In [ ]:
import numpy as np
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# **np.ones and np.zeros and np.randoms**

In [ ]:
a=np.ones((3,3))
b=np.zeros((3,3))
c=np.random.random((3,3))
print(a)
print(b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.58347533 0.35344162 0.06669279]
 [0.17702406 0.74144257 0.73103077]
 [0.1874983  0.44757702 0.81409385]]


## **np.identity** **or np.eye**

In [ ]:
# identity matrics bnany k liya identity function kaa use hota hai identity matirx hmesha square matrix hota hai 2x2 3x3
# agr mai chahtaa hoo koi b type kaa matrix banao jis mai diagnols jo hain wo 1 hoo jesy 2x3 yaa 4x5 tu mai np.eye ka use kr sktaa hoo
np.identity(4)
np.eye(5,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

# **size**

In [ ]:
# size is liya use hotaa hai  k jb hum matrix ka size jana chahty hoo size kaa use matrix mai elements kitny hain yai jany k liya use hota hai
arr=np.array([[1,2,3],[4,5,6]])
arr.size

6

# **item size**

In [ ]:
# item size btata hai k hr item memory mai kitna size occupy kr raha hai
arr.itemsize

8

# **int32 or int 64**
# int32: 32 bits, range chhoti (-2.1 billion to 2.1 billion), kam memory, fast processing.
# int64: 64 bits, range badi (-9.2 quintillion to 9.2 quintillion), zyada memory, bada number support

# **astype**
# astype memory ko bachany k liya use krty hain for example agr ak iten kam memory mai b kam kr  skta haii tu os sy kam memory mai he kam ly gy hum tu os k liya astype use hota hai jesy k ak float mai  pri hai age 32.3 tu .3 ka hum ny kiya krna hum astype use kry gy or os ko int32 mai convert kr ly gy jis sy hmari memory bach jy giii

In [ ]:
arr.astype('int32')
b=arr.astype(np.int64)
print(b)

[[1 2 3]
 [4 5 6]]


# **Array operations**

# **SCalar operations**

In [ ]:
# scaler operation ka mtlb single number k sth operation krna
# Arithmetic operation sary arithmatic operators kam krty hain
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(10,19).reshape(3,3)
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
# Rational operators
arr1>15
arr1==3
# koi b comparison operator use ho sktaa hai is jaga pr



array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

# **Vector operations**

In [ ]:
# arithmatic
arr1**arr1
# mtlb k du matrices ko hum mila k kam kr skty hain

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [ ]:
arr1>arr2
# mtlb k koi b comparison b kr skty hain

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# **Array functions**

In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[43., 95., 72.],
       [92.,  0., 48.],
       [70., 83., 98.]])

In [ ]:
# max/min/sum/product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

98.0
0.0
601.0
0.0


In [ ]:
# flexibility itni dyta hai k hum hr  row ya hr column mai sy nikal skty hain
# 0 --> column or 1--> ka mtlb hota hai row
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))
print(np.prod(a1,axis=0))


[92. 95. 98.]
[95. 92. 98.]
[276920.      0. 338688.]


In [ ]:
# mean/mode/median/std/var
print(np.mean(a1,axis=1))
print(np.median(a1,axis=0))
print(np.std(a1,axis=1))
print(np.var(a1,axis=0))
print(a1)

[70.         46.66666667 83.66666667]
[70. 83. 72.]
[21.27596453 37.57067414 11.4406682 ]
[ 401.55555556 1784.22222222  416.88888889]
[[43. 95. 72.]
 [92.  0. 48.]
 [70. 83. 98.]]


In [ ]:
# trignomatric function b use hoty hain
# sary k sary trignometrics function use kr skty hain
print(np.sin(arr1))


[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
# we can calculate dot product
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(10,16).reshape(3,2)
a1.dot(a2)


array([[ 76,  82],
       [184, 199],
       [292, 316]])

In [ ]:
# log and exponents
print(np.exp(a1))
print(np.log(a1))


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [ ]:
# round/floor/ceil
# ciel agy waly integer pr fenkta hai
# floor pichy waly integer pr fenkta hai
# round nearest pr fenktaa hai
print(np.round(np.random.random((2,3))))
print(np.floor(np.random.random((2,3))))
print(np.ceil(np.random.random((2,3))))

[[0. 0. 1.]
 [1. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(arr[0::2,1::2])
print(arr[1,0::3])

[[ 1  3]
 [ 9 11]]
[4 7]


In [ ]:
a3=np.arange(27).reshape(3,3,3)
print(a3)
print(a3[2,2:,1:])
# iteration nditer b use hota hai
for i in a3:
  for j in i:
    for k in j:
      print(k)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[25 26]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
np.random.random()

0.5064433929916082

# NUmpy arrays vs Python lists **  

In [ ]:
# speed
# list
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)

11.413894653320312


In [ ]:
# NOW we will do with numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.4291353225708008


In [ ]:
11.413894653320312/0.4291353225708008

26.597425224620594

In [ ]:
# memory advantage
a=[i for i in range(10000000)]
import sys
sys.getsizeof(a)



89095160

In [ ]:
import numpy as np
arr=np.arange(10000000, dtype=np.int16)
sys.getsizeof(arr)


20000112

In [ ]:
# Fancy indexing
arr=np.arange(0,18).reshape(2,3,3)
print(arr)
print(arr[[1,3],[2,3]])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
# Boolean indexing
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[44, 37, 88, 57],
       [52, 36, 53, 50],
       [22, 35, 27,  6],
       [83, 53, 31, 42],
       [63, 61, 38, 63],
       [87, 10, 92, 46]])

In [ ]:
a>50

array([[False, False,  True,  True],
       [ True, False,  True, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False,  True],
       [ True, False,  True, False]])

In [ ]:
# Find all numbers greater then 50
# yai hoti hai boolean indexing jis mai hum formula laga k apni mrzi k numbers nikal skty hain
print(a[a>50])
print(a[(a>50)& (a%2==0)])
# find the numbers that are not divisible by 7
print(a[~(a%7==0)])


[88 57 52 53 83 53 63 61 63 87 92]
[88 52 92]
[44 37 88 57 52 36 53 50 22 27  6 83 53 31 61 38 87 10 92 46]


# **Broadcasting**
agr dono ka dimension same ni hai tu hum dimansion brhay gy by adding one in front (1,1,3) asy kr k or phr 1 brhta jay gaa khud b khud hee
# Same Shape Ho Toh Operation Hojayega: Agar dono arrays ka shape bilkul same ho, toh woh seedha operation mein chalayenge aur har element ka operation apne corresponding element ke saath hoga. Isme kisi special rule ki zaroorat nahi.

# Ek Dimension Ka Size Agar 1 Ho Toh Expand Ho Sakta Hai: Agar dono arrays ke shapes different hain, toh bhi operation ho sakta hai lekin sirf tab jab chhoti array ka size kisi dimension mein 1 ho. NumPy us dimension ko "stretch" kar ke doosre array ke size ke barabar kar dega. Matlab, agar ek array ka size 1 hai, toh woh size automatically badh sakta hai.

# Shuru Se Shapes Compare Karna: Agar arrays ke dimensions ka number different hai (jaise ek 2D hai aur doosra 3D), toh chhoti array ke shape ke shuru mein 1 add kiya jata hai taake dono arrays ke dimensions equal ho jayein. Is tarah dono arrays ka dimension equal ho jaata hai aur compare ho sakte hain.

# Her Dimension Mein Size Ya Toh Same Ya Phir 1 Hona Chahiye: Har dimension mein ya toh dono arrays ka size same hona chahiye ya phir ek ka size 1 hona chahiye. Agar kisi bhi dimension mein ye rule break hota hai, toh broadcasting kaam nahi karegi aur ValueError aayega. **bold text**


In [ ]:
#Add a Constant to Each Element of a Matrix
# Ek 3x3 matrix banayein aur har element mein ek constant (for example, 5) add karne ke liye broadcasting use karen
matrix = np.arange(1,10).reshape(3,3)
constant=5
result=matrix+constant
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# 2. Row-Wise Addition in a Matrix
# Ek 4x3 matrix aur ek 1D array create karen jo 3 elements ka ho (ek row ke equal). Phir, is 1D array ko matrix ke har row mein add karne ke liye broadcasting ka use karen
matrix= np.arange(0,12).reshape(4,3)
matrix2=np.arange(0,3).reshape(1,3)
print(matrix+matrix2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
# Column-Wise Multiplication in a Matrix
# Ek 3x4 matrix aur ek 1D array banayein jo 3 elements ka ho (ek column ke equal). Phir, is array ko matrix ke har column mein multiply karne ke liye broadcasting ka use karen.
matrix=np.arange(0,12).reshape(3,4)
matrix1=np.arange(0,3).reshape(3,1)
print(matrix)
print(matrix1)
print(matrix*matrix1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]
[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]


In [ ]:
# Outer Product of Two Vectors
# Do 1D arrays banayein (for example, [1, 2, 3] aur [4, 5, 6]). Inka outer product calculate karne ke liye broadcasting use karen, jisse ek 3x3 matrix mile jismein har element array1[i] * array2[j] ho.
arr1=np.arange(1,4)
arr2=np.arange(4,7)
array=np.outer(arr1,arr2)
print(array)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
a=np.arange(16).reshape(4,4)#yai nahi hoo sktaa hai q k yai expend nahi kiya jaa sktaa
b=np.arange(12).reshape(4,3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (4,4) (4,3) 

In [ ]:
a=np.arange(16).reshape(4,4)
b=np.arange(4).reshape(1,4)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]


In [ ]:
arr1 = np.array([[[1]], [[2]], [[3]]])  # Shape (3, 1, 1)
arr2 = np.array([[10, 20]])             # Shape (1, 1, 2)

# Broadcasting works because arr1 has 1s in the second and third dimensions, and arr2 has 1 in the first dimension
result = arr1 + arr2
# Resulting shape will be (3, 1, 2)
result

array([[[11, 21]],

       [[12, 22]],

       [[13, 23]]])

In [ ]:
import urllib.request
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return 